version: '3'
services:
  database:
    image: ubuntu/postgres:latest
    container_name: contractor-postgres
    user: postgres
    profiles: ["debug"]
    hostname: localhost
    ports:
      - "8001:5432"
    env_file:
      - config.env
    volumes:
      - ../data:/home/ubuntu
  app:
    image: my_test_python:latest
    container_name: contractor-app
    hostname: localhost
    env_file:
      - config.env
    volumes:
      - .:/home/ubuntu
    args:
      - python3
      - contractor_db.py
      - TN